server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: inventario-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/almacen/**
            - Path=/api/categoria/**
            - Path=/api/productos/**
            - Path=/api/stock/**
#        - id: customer-service
#          uri: lb://customer-service
#          predicates:
#            - Path=/api/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

